name: Vue Continous Integration 2

on: 
  pull_request:
    branches: [master]

jobs:
  test_pull_request:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./client
    steps:
      - name: Checkout
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
      - name: 'UI Tests - Headless'
        uses: cypress-io/github-action@2.9.7
      - run: npm install
      - run: npm start
