name: Vue Continous Integration

on: 
  pull_request:
    branches: [developer]

jobs:
  test_pull_request:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          path: "Knitli/client"
      - uses: actions/setup-node@master
        with:
          path: "Knitli/client"
          node-version: 12
      - run: npm install
      - run: npm run serve
