name: Vue Continous Integration 

on: 
  push:
    branches: [developer]

jobs:
  test_pull_request:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./client
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - uses: actions/setup-node@master
      - name: Cypress.io
        uses: cypress-io/github-action@2.9.7
      - run: npm install
      - run: npm start
