name: Vue Continous Integration 2

on: 
  pull_request:
    branches: [developer]

jobs:
  test_pull_request:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./client
    steps:
      - name: Checkout
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
      - run: npm install
      - name: Cupress.io
      - uses: cypress-io/github-action@master
        with:
          start: ng serve

