name: Vue Continous Integration 

on: 
  push:
    branches: [developer]

jobs:
  Frontend_Test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./client
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Setting up Node
        uses: actions/setup-node@master
      - name: Installing dependencies
        run: npm install
      
      - name: Executing Cypress Tests
        uses: cypress-io/github-action@master
        with:
          working-directory: ./client
          headless: true
          wait-on: 'http://localhost:4200'
          start: npm start

